---

- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"

- name: Check if consul installed
  stat: path=/tmp/consul-template_0.15.0_linux_amd64.zip
  register: st

- name: Download consul-template
  get_url:
    url: https://releases.hashicorp.com/consul-template/0.15.0/consul-template_0.15.0_linux_amd64.zip
    dest: /tmp/
    mode: 0755
  when: st.stat.exists == False

- name: Check if consul installed
  stat: path=/usr/local/bin/consul-template
  register: st

- name: Install consul
  unarchive: src="/tmp/consul-template_0.15.0_linux_amd64.zip" dest="/usr/local/bin" remote_src=yes
  when: st.stat.exists == False