---

- name: Check if etcd installed
  stat: path=/usr/local/bin/etcd
  register: st

- name: Check if etcd Download
  stat: path=/tmp/etcd-v3.0.6-linux-amd64.tar.gz
  register: etcd_st

- name: Download etcd
  get_url: url=https://github.com/coreos/etcd/releases/download/v3.0.6/etcd-v3.0.6-linux-amd64.tar.gz dest=/tmp
  when: st.stat.exists == False and etcd_st.stat.exists == False

- name: Check if etcd Download
  stat: path=/tmp/etcd-v3.0.6-linux-amd64.tar.gz
  register: etcd_st

- name: Install etcd
  unarchive: src="/tmp/etcd-v3.0.6-linux-amd64.tar.gz" dest="/tmp/" remote_src=yes copy=no
  when: etcd_st.stat.exists

- name: Move etcd to bin
  command: mv /tmp/etcd-v3.0.6-linux-amd64/etcd /usr/local/bin
  when: st.stat.exists == False

- name: Move etcd to bin
  command: mv /tmp/etcd-v3.0.6-linux-amd64/etcdctl /usr/local/bin
  when: st.stat.exists == False

- name: Clean up etcd.
  command: rm -rf /tmp/etcd-v3.0.6-linux-amd64 state=absent

- name: Configuring etcd cluster.
  shell: "nohup /usr/local/bin/etcd --name {{ ansible_hostname }} --initial-advertise-peer-urls http://{{ ip }}:2380 \
    --listen-peer-urls http://{{ ip }}:2380 \
    --listen-client-urls http://{{ ip }}:2379,http://127.0.0.1:2379 \
    --advertise-client-urls http://{{ ip }}:2379 \
    --initial-cluster-token {{ cluster_token }} \
    --initial-cluster {{ cluster_node_1 }},{{ cluster_node_2 }},{{ cluster_node_3 }} \
    --initial-cluster-state new > /home/vagrant/etcd.out 2>&1 &"

