---
- name: Add Docker repository.
  yum_repository:
    name: docker
    description: Docker Repository
    enabled: 1
    gpgcheck: 1
    baseurl: "{{ docker_repository_baseurl }}"
    gpgkey: "{{ docker_repository_gpgkey }}"
    
- name: Install the Docker package.
  yum: name=docker-engine state=present

- name: Ensure docker group present
  group: name=docker state=present

- name: Add docker group
  user: name=vagrant group=docker

- name: Ensure docker engine start automaticlly after vm reboot
  command: chkconfig docker on

- name: Start docker service
  service: name=docker state=started  

