---
# This is the main playbook what ansible will use for provisoning. 
- hosts: etcd-cluster
  remote_user: vagrant
  serial: 1
  roles:
    - consul
    - dockerengine
    - registrator-consul
    - consul-template

    
    
