- name: Directories are created
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
  with_items: "{{ directories }}"


#- name: Files are copied
#  copy:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    mode: "{{ item.mode }}"
#  with_items: files
#
#- name: Download Confd
#  get_url:
#    url: https://github.com/kelseyhightower/confd/releases/download/v0.12.0-alpha3/confd-0.12.0-alpha3-linux-amd64
#    dest: /usr/local/bin/confd
#    mode: 0755